name: DeZeroUnityTest
on:
  [push]
jobs:
  TestFunctions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - DeZeroUnity
        unityVersion:
          - 2021.3.15f1
        testMode:
          - editmode
    steps:
      - run: echo "DeZeroUnityTest Start"
      # Actionsがリポジトリにアクセスできるようにしている
      - uses: actions/checkout@v3
      # Libraryをキャッシュすることで高速化している
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env: 
          UNITY_LISENCE: ${{secrets.UNITY_LICENSE}}
        with:
          customParameters: '-nographics'
          projectPath: ${{ matrix.projectPath }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: ${{ matrix.testMode }}
          unityVersion: ${{ matrix.unityVersion}}
      - run: echo "This job's status is ${{ job.status }}."