name: DeZeroUnityTest
on:
  [push]
jobs:
  TestDeZeroUnity:
    runs-on: ubuntu-latest
    steps:
      - run: echo "DeZeroUnityTest Start"
      # Actionsがリポジトリにアクセスできるようにする
      - uses: actions/checkout@v3
      # Libraryをキャッシュすることで高速化する
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env: 
          UNITY_LISENCE: ${{ secrets.UNITY_LICENSE }}
        with:
          customParameters: '-nographics'
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: editMode
          unityVersion: 2021.3.15f1
      - run: echo "This job's status is ${{ job.status }}."